### ISSUE TITLE
Module status

### ISSUE THREAD

**Issue by daviddias** [dignifiedquire/borc#22]
@dignifiedquire, borc going to get merged in node-cbor? If yes, when? If not, can we have borc on the IPFS org so that it is easier to maintain? Thanks!

**Comment by dignifiedquire** [comment]
I don't think it will be merged anytime soon, given the amount of work needed to make that happen

**Comment by daviddias** [comment]
@dignifiedquire wanna move this one to ipfs-shipyard to make it more easy to maintain? Right now we can't add labels or assign to people or change CI things

**Comment by dignifiedquire** [comment]
@diasdavid I just tried but I don’t have permission on ipfs-shipyard

**Comment by daviddias** [comment]
@dignifiedquire just added you to the shipyard-maintainers team, you should have perms now.

**Comment by batjko** [comment]
There hasn't been a lot of movement on this repo recently. Is it no longer being maintained or has this work to merge it with a different repo happened in the meantime?

**Comment by dignifiedquire** [comment]
It will be a large chunk of work to merge this into the original node-cbor, which might or might not make sense. Some background here: https://github.com/hildjj/node-cbor/pull/41

I don't have time to work on this currently, and the ideas that I have to improve this module like #26 would make this probably even more complicated. That said if someone has the time to get the two merged I would be all for it.

**Comment by dignifiedquire** [comment]
For now, this module is stable and can be relied upon in terms of the features it implements

**Comment by daviddias** [comment]
Is there still a valid reason to have a fork? I'm not sure anymore on why there was a reason for one in the first place.

Also, seems that @hildjj has been giving node-cbor a lot of attention and it would be better to have both efforts combined :)

**Comment by dignifiedquire** [comment]
@daviddias node-cbor is still nowhere close to the performance of this module. So I would say yes. 

Benchmarks with the latest versions on my machine.

```
encode - node-cbor - 76 x 1,060 ops/sec ±23.21% (66 runs sampled)
encode - borc - 76 x 22,337 ops/sec ±3.63% (80 runs sampled)
encode - stream - borc - 76 x 5,384 ops/sec ±20.56% (65 runs sampled)
encode - JSON.stringify - 76 x 27,491 ops/sec ±15.25% (70 runs sampled)
decode - node-cbor - 47 x 2,477 ops/sec ±3.70% (78 runs sampled)
decode - borc - 47 x 24,218 ops/sec ±14.53% (60 runs sampled)
decode - JSON.parse - 47 x 49,681 ops/sec ±12.95% (62 runs sampled)
```

We are talking a difference of 10-12x in performance difference on Node@10

**Comment by vmx** [comment]
@daviddias We also want to change the behaviour (e.g. #36) and also switch dependencies (e.g. #37) so I think a fork still makes sene. Though I agree that having only one JS CBOR implementation would be great.

**Comment by hildjj** [comment]
I'm happy to switch to jsbi, assuming it has roughly similar features (https://github.com/hildjj/node-cbor/issues/90).  I'm also happy to add an option for serializing `undefined` in multiple different ways, including throwing an error (https://github.com/hildjj/node-cbor/issues/91).

**Comment by hildjj** [comment]
That leaves perf, which I'm open to changing.  The biggest issue is likely how async and stream-oriented I wanted to be.  There's a pending patch for that which has been waiting long enough that it doesn't apply anymore, but I'm open to suggestions for a faster, sync-only mode for parsing that still reuses as much of the infrastructure as possible.

**Comment by vmx** [comment]
@hildjj That's great to hear. I'm still new to the code base, but I'll have a look. Joining efforts just makes so much sense.

**Comment by hildjj** [comment]
Note for the future, I've moved most of my cbor efforts to [cbor2](https://github.com/hildjj/cbor2).
