### ISSUE TITLE
Add P* (P0, P1, P2, P3, P4) labels

### ISSUE THREAD

**Issue by daviddias** [dignifiedquire/borc#23]
@VictorBjelkholm could you add the P* labels to this repo as well?

**Comment by daviddias** [comment]
ping @VictorBjelkholm

**Comment by victorb** [comment]
Can we move this fork into the organization which this is being used from? [The syncing script for labels](https://github.com/ipfs/pm/tree/master/tools/sync-labels) only work on repositories where the user (me, if I'm running the script) has write access to.

**Comment by daviddias** [comment]
Agreed. Same request here https://github.com/dignifiedquire/borc/issues/22#issuecomment-360870441
