### ISSUE TITLE
use jsbi instead of bignumber

### ISSUE THREAD

**Issue by hugomrdias** [dignifiedquire/borc#37]
In the context of OKR work to reduce browser bundle sizes of IPFS packages, i found that different big int packages are used in several of our repos.
I would like to propose the use of https://github.com/GoogleChromeLabs/jsbi everywhere we control. 

JSBI is a pure-JavaScript implementation of the official ECMAScript BigInt proposal, which is on track to become a part of the JavaScript language in the near future.

Its advantages over other, existing big-integer libraries are:

- it behaves exactly like native BigInts will when they become available, so to migrate to those, you can mechanically update your code’s syntax; no re-thinking of its logic will be required. 
- strong focus on performance. On average, JSBI is performance-competitive with the native implementation that Google Chrome is currently shipping.
- Once BigInts are natively supported everywhere, we can use babel-plugin-transform-jsbi-to-bigint to transpile your JSBI code into native BigInt code once and for all.

jsbi isn't the smallest big int package but it's good enough, plus if we only jsbi across all packages the gains in size will be significant. 

refs:
https://github.com/GoogleChromeLabs/jsbi
https://v8.dev/blog/bigint
https://github.com/tc39/proposal-bigint

//cc @vmx

**Comment by hildjj** [comment]
How are you going to handle float bignumbers?

**Comment by vmx** [comment]
@hildjj Good point. I exactly ran into this issue 10mins ago and have no idea :)

I've pushed my current work though at https://github.com/dignifiedquire/borc/tree/switch-to-jsbi. The decimal tests are currently commented out.

@hildjj Good to hear from you. I'd be more than happy to work together on a single CBOR implementation if we find agreement on the points where the current implementations diverged.

**Comment by dignifiedquire** [comment]
@hugomrdias why was this closed?

**Comment by hugomrdias** [comment]
because we need floats and to use jsbi (Big Int) we would need to build something on top of it to encode/decode floats in BigInts.

basically the OP idea doesn't work directly, would be nice to use jsbi but for now we should keep bignumber and use it everywhere.
