### ISSUE TITLE
Extra bytes won't throw an error

### ISSUE THREAD

**Issue by rllola** [dignifiedquire/borc#47]
I have tested with extra bytes added at the end of the CBOR. I was expecting to have an error throw but nothing.

Extra bytes could mean that there is an error in the CBOR and should probably throw something instead of being silence.

**Comment by rvagg** [comment]
Can you outline the specific case that does this? I can't reproduce it:

```
> borc.decode(Buffer.concat([borc.encode({a:'cbor',string:true}), crypto.randomBytes(32)]))
Uncaught Error: Undeterminated nesting
```

**Comment by rllola** [comment]
Yep.
Here my specific case : 
```javascript
const cbor = require('borc');
const unvalid_cbor = "89005501fd1d0f4dfcd7e99afcb99a8326b7dc459d32c62855011eaf1c8a4bbfeeb0870b1745b1f57503470b71160144000186a0430009c41961a80040" + "00";
const buf = Buffer.from(unvalid_cbor, 'hex');
cbor.decodeFirst(buf);
```

An I have a normal answer : 
```
[
  0,
  <Buffer 01 fd 1d 0f 4d fc d7 e9 9a fc b9 9a 83 26 b7 dc 45 9d 32 c6 28>,
  <Buffer 01 1e af 1c 8a 4b bf ee b0 87 0b 17 45 b1 f5 75 03 47 0b 71 16>,
  1,
  <Buffer 00 01 86 a0>,
  <Buffer 00 09 c4>,
  25000,
  0,
  <Buffer >
]
```

**Comment by rvagg** [comment]
mmmm, confirmed, there's certain values of the extra bytes which it parses successfully and others that it throws an error on. Change it to `39` and it throws a `Failed to parse`.

If I change my example above to a non-random string in the right range I can get the same effect:

`borc.decode(Buffer.concat([borc.encode({a:'cbor',string:true}), Buffer.alloc(10)]))` -> `{ a: 'cbor', string: true }`

**Comment by rvagg** [comment]
Ah, ok, so what's happening is that borc will decode _everything_ that it finds if it can and treat the top-level as an implicit array.

So what's happening with  `borc.decode(Buffer.from('89005501fd1d0f4dfcd7e99afcb99a8326b7dc459d32c62855011eaf1c8a4bbfeeb0870b1745b1f57503470b71160144000186a0430009c41961a80040' + '00', 'hex'))` is that it pulls out two top-level objects, one a map and one a single uint=0.

`decode()` and `decodeFirst()` are essentially the same thing and will only return you the _first_ object that it finds.

What you probably want to do is `decodeAll()` and inspect the resulting array and apply appropriate strictness criteria to it.

`borc.decodeAll(Buffer.from('89005501fd1d0f4dfcd7e99afcb99a8326b7dc459d32c62855011eaf1c8a4bbfeeb0870b1745b1f57503470b71160144000186a0430009c41961a80040' + '00', 'hex'))`

returns:

```
[
  [
    0,
    <Buffer 01 fd 1d 0f 4d fc d7 e9 9a fc b9 9a 83 26 b7 dc 45 9d 32 c6 28>,
    <Buffer 01 1e af 1c 8a 4b bf ee b0 87 0b 17 45 b1 f5 75 03 47 0b 71 16>,
    1,
    <Buffer 00 01 86 a0>,
    <Buffer 00 09 c4>,
    25000,
    0,
    <Buffer >
  ],  0
]
```

So if you want to be strict and say "I expect that the bytes I decode are a single top-level object" then you should `d = decodeAll(...)` and assert on `d.length === 1`, then pull out `d[0]`.

I think this comes from the tension between 3.1 (streaming) and 3.2 (generic / well-formed) in the CBOR spec and the origin of borc being in https://github.com/hildjj/node-cbor which offers a streaming mode.

**Comment by rvagg** [comment]
btw @rllola, if you're doing this for Filecoin, you might want to consider whether the JS IPLD libraries are worth using since Filecoin uses IPLD and we have a suite of tools to deal with all things IPLD over at https://github.com/ipld

I've proposed including this strictness check in ipld-dag-cbor @ https://github.com/ipld/js-ipld-dag-cbor/pull/130 and calling this out explicitly in the DAG-CBOR spec @ https://github.com/ipld/specs/pull/268 since this ambiguity exists in the wild.

**Comment by rllola** [comment]
Hey @rvagg ,
I have switched to `js-ipld-dag-cbor` and it still doesn't throw when I append `00` at the end of the cbor message... However I have seen you added a test and it looks good to me.

I am gonna play a little with the lib and I hope I will find my mistake. I just wanted to keep you updated on this.

**Comment by rllola** [comment]
Ok I have found my error. The latest release didn't include this fix. I was too impatient.
